### ISSUE TITLE
missing price_origin filter = R (tbc constante in claim module)

### ISSUE THREAD

**Issue by delcroip** [openimis/openimis-be-calcrule_third_party_payment_py#9]
https://github.com/openimis/openimis-be-calcrule_third_party_payment_py/blob/7e41b97f783c0c99c473aa6db78047df1d73f875/calcrule_third_party_payment/utils.py#L86

**Comment by delcroip** [comment]
relative_items= items.filter(price_origin = 'R')
relative_services= servcies.filter(price_origin = 'R')
getaggregate in relative....
update relative...

**Comment by sniedzielski** [comment]
@delcroip As I mentioned on you on Skype - there is constant for this 'R'  defined in Product module. I've pushed this on feature/OTC-594 branch already. https://github.com/openimis/openimis-be-calcrule_third_party_payment_py/commit/60766697151e3e25ce7b98fc76855390b1755353
